# File: src/main/resources/config.properties
db.url=jdbc:mysql://localhost:3306/yophonedb
db.user=root
db.pass=
file.folder=C:\\Users\\Admin\\Desktop\\ServerFolder
socket.host=0.0.0.0
socket.port=8081
file.server.port=8082
bcrypt.salt=shikanoko

cloudinary.cloud-name=dglbu6wpt
cloudinary.api-key=277219654386383
cloudinary.api-secret=We2SUWdg67VUKTCYkgnMoopNIrc
cloudinary.secure=true